LIONGRAM/config/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from posts.views import index, url_view, url_parameter_view, funtion_view, class_view, post_list_view, post_detail_view, post_create_view, post_update_view, post_delete_view 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('url/', url_view),
    path('url/<str:username>/', url_parameter_view),
    path('fbv/', funtion_view),
    path('cbv/', class_view.as_view()),


    path('',index, name='index'),
    path('posts/', include('posts.urls', namespace='posts')),

    path('__debug__/', include('debug_toolbar.urls')),


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LIONGRAM/posts/urls.py
from django.urls import path
from .views import post_list_view, post_create_view, post_create_form_view, post_update_view, post_delete_view, post_detail_view

app_name = 'posts'

urlpatterns = [
    path('', post_list_view, name='post-list'),
    path('new/',post_create_view, name='post-create'),
    path('create/',post_create_form_view, name='post-create'),

    path('<int:id>/', post_detail_view, name='post-detail'),
    path('<int:id>/edit/',post_update_view, name='post-update'),
    path('<int:id>/delete/', post_delete_view, name='post-delete')
]

LIONGRAM/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Post(models.Model):
    image = models.ImageField(verbose_name="Image", null=True, blank=True)
    content = models.TextField(verbose_name="Content")
    created_at = models.DateTimeField(verbose_name="작성일", auto_now_add=True)
    view_count = models.IntegerField(verbose_name="View Count", default=0)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)


class Comment(models.Model):
    content = models.TextField(verbose_name="내용")
    created_at = models.DateTimeField(verbose_name="작성일")
    post = models.ForeignKey(to="Post", on_delete=models.CASCADE)
    writer = models.ForeignKey(to=User, on_delete=models.CASCADE, null=True, blank=True)

LIONGRAM/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    phone = models.CharField(verbose_name='phoneNum', max_length=11)

class UserInfo(models.Model):
    phone_sub = models.CharField(verbose_name='보조전화번호', max_length=11)

    user = models.ForeignKey(to='User', on_delete=models.CASCADE)

LIONGRAM/posts/forms.py
from django import forms

from .models import Post

# class PostBaseForm(forms.Form):
#     CATEGORY_CHOICES = [
#         ('1', '일반'),
#         ('2', '계정'),
#     ]
#     image = forms.ImageField(label='이미지')
#     content = forms.CharField(label='내용', widget=forms.Textarea, required=True)
#     # category = forms.ChoiceField(label='카테고리', choices=CATEGORY_CHOICES)

class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

from django.core.exceptions import ValidationError
class PostCreateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields = ['image', 'content']
    
    def clean_content(self):
        data = self.cleaned_data['content']
        if "비속어" == data:
            raise ValidationError("'비속어'는 사용하실 수 없습니다.")

        return data

class PostUpdateForm(PostBaseForm):
    class Meta(PostBaseForm.Meta):
        fields= ['image', 'content']
    
class PostDetailForm(PostBaseForm):
    def __init__(self, *args, **kwargs):
        super(PostDetailForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].widget.attrs['disabled'] = True

LIONGRAM/posts/views.py
from wsgiref.util import request_uri
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404, HttpResponse, JsonResponse
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required

from .forms import PostBaseForm, PostCreateForm, PostDetailForm
from .models import Post

def index(request):
    post_list = Post.objects.all().order_by('-created_at') #Post 전체 조회 / 최신순으로 정렬 order_by('-created_at')
    context = {
            "post_list" : post_list
        }
    return render(request, 'index.html', context)

def post_list_view(request):
    # post_list = Post.objects.all() #Post 전체 조회
    post_list = Post.objects.filter(writer=request.user) #Post.writer가 현재 로그인인 것 조회
    context = {
        "post_list" : post_list
    }
    return render(request, 'posts/post_list.html', context)

def post_detail_view(request, id):
    try:
        post = Post.objects.get(id=id)
    except Post.DoesNotExist:
        return redirect('index')
    context = {
        'post' : post,
        'form' : PostDetailForm(),
    }
    return render(request, 'posts/post_detail.html', context)

@login_required # 이 함수는 로그인했을때만 처리한다
def post_create_view(request):
    if request.method == 'GET':
        return render(request, 'posts/post_form.html')
    else:
        image = request.FILES.get('image')
        content = request.POST.get('content')
        print(image)
        print(content)
        Post.objects.create(
            image=image,
            content=content,
            writer=request.user,
        )
        return redirect('index') 

def post_create_form_view(request):
    if request.method == 'GET':
        form = PostCreateForm()
        context = {'form': form}
        return render(request, 'posts/post_form2.html', context)
    else:
        form = PostCreateForm(request.POST, request.FILES)
        
        if form.is_valid():
            Post.objects.create(
                image=form.cleaned_data['image'],
                content=form.cleaned_data['content'],
                writer=request.user
            )
        else:
            return redirect('posts:post-create')
        return redirect('index')

def post_update_view(request,id):
    # post = Post.objects.get(id=id)
    post = get_object_or_404(Post, id=id)
    if request.method == 'GET':
        context = { 'post':post }
        return render(request, 'posts/post_form.html', context)
    elif request.method == 'POST':
        new_image = request.FILES.get('image')
        content = request.POST.get('content')
        print(new_image)
        print(content)

        if new_image:
            post.image.delete()
            post.image = new_image

        post.content = content
        post.save()
        return redirect('posts:post-detail', post.id)

def post_delete_view(request, id):
    post = get_object_or_404(Post, id=id)
    if request.user != post.writer:
        return Http404('잘못된 접근입니다다다!!')
    
    if request.method == "GET":
        context = { 'post' : post }
        # print(post.id)
        return render(request, 'posts/post_confirm_delete.html', context)
    else:
        post.delete()
        return redirect('index')

def url_view(request):
    print('url_view()') #브라우저에서 새로고침해보면 터미널에 찍힌다.
    data = {'code':'001', 'msg':'ok'}
    # return HttpResponse('url_view')
    return JsonResponse(data)

def url_parameter_view(request, username):
    print('url_parameter_view()')
    print(f'username: {username}')
    print(f'request.GET: {request.GET}')
    # print(username)
    # print(request.GET)
    return HttpResponse(username)

def funtion_view(request):
    print(f'request.method: {request.method}')
    if request.method == 'GET':
        print(f'request.GET: {request.GET}')
    elif request.method == 'POST':
        print(f'request.POST: {request.POST}')
    return render(request, 'view.html')

class class_view(ListView):
    model = Post
    template_name = 'cbv_view.html'
    ordering = ['-id']

LIONGRAM/users/views.py
from django.shortcuts import render

# Create your views here.

LIONGRAM/posts/templates/cbv_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for object in object_list %}
        <p>{{ object }}</p>
    {% endfor %}
</body>
</html>

LIONGRAM/posts/templates/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="/fbv/">새로고침</a><br>
    <form action="" method="GET">
        <input type="text" name="var">
        <input type="submit" value="GET 제출">
    </form>

    <form action="" method="POST"> {% csrf_token %}
        <input type="text" name="var">
        <input type="submit" value="POST 제출">
    </form>


</body>
</html>

LIONGRAM/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | 라이언그램</title>
</head>
<body class="container">
    <div>
    {% block content %}
    {% endblock %}
    </div>
    <div>
        <nav>
            <ul class="bottom-menu-group">
                <li>
                    <a href="{% url 'index' %}">
                        <img src="{% static 'icons/home_outlined_black_36dp.svg' %}" alt="Home">
                    </a>
                </li>
                <li><img src="{% static 'icons/search_outlined_black_36dp.svg' %}" alt="Search"></li>
                <li>
                    <a href="{% url 'posts:post-create' %}">
                        <img src="{% static 'icons/add_box_outlined_black_36dp.svg' %}" alt="Post">
                    </a>
                </li>
                <li><img src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="Like"></li>
                <li><img src="{% static 'icons/account_circle_outlined_black_36dp.svg' %}" alt="Profile"></li>
            </ul>
        </nav>
    </div>
</body>
</html>

LIONGRAM/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home {% endblock %}

{% block content %}
<main>
    <div class="card-list">
        {% for post in post_list %}
            {% include 'mixin/posts/post_card.html' with detail=False %}
        {% endfor %}
    </div>
</main>
{% endblock %}

LIONGRAM/templates/mixin/posts/post_card.html
{% load static %}

<div class="card">
    <div class="card__header">
        <img src="http://via.placeholder.com/32x32" alt="profile_image">
        <a href="#">
            <span class="card__user-name">{{ post.writer }}</span>
        </a>
        {% if request.user == post.writer %}
            <a href="{% url 'posts:post-update' post.id %}"> 수정하기 </a> | 
            <a href="{% url 'posts:post-delete' post.id %}"> 삭제하기 </a>
        {% endif %}
    </div>
    <div class="card__body">
        <div>
            {% if post.image %}
                <img class="card__image" src="{{ post.image.url }}" alt="card_image">
            {% else %}
                <img class="card__image" src="http://via.placeholder.com/600x600" alt="">
            {% endif %}
        </div>
        <div class="card__btn-group">
            <div>
                <img class="card__btn" src="{% static 'icons/favorite_outlined_black_36dp.svg' %}" alt="좋아요">
                <img class="card__btn" src="{% static 'icons/mode_comment_outlined_black_36dp.svg' %}" alt="댓글">
                <img class="card__btn" src="{% static 'icons/send_outlined_black_36dp.svg' %}" alt="공유하기">
            </div>
            <div>
                <img class="card__btn" src="{% static 'icons/bookmark_outlined_black_36dp.svg' %}" alt="북마크">
            </div>
        </div>
        <div class="card_content"> 
            <span class="card__like-num">좋아요 00개</span> 
            <div class="card__main-text">
                <p><span class="card__user-name">{{ post.writer }}</span>
                    {% if not detail %}
                        {{post.content|truncatechars:35}}
                    {% else %}
                        {{post.content}}
                    {% endif %}
                </p>
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">더보기</a>
                {% endif %}
                <!-- /posts/{{post.id}} -->
            <div>
                <p>댓글 {{ post.comment_set.all.count }}개
                {% if not detail %}
                    <a href="{% url 'posts:post-detail' post.id %}">모두 보기</a>
                {% endif %}
                </p>
                <ul class="card__comment-group">
                    {% if not detail %}
                        {% for comment in post.comment_set.all|slice:":2" %}
                        <li>
                            <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p> 
                        </li>
                        {% endfor %}
                    {% else %}
                        {% for comment in post.comment_set.all %}
                        <li>
                            <p><span class="card__user-name">{{ comment.writer }}</span>{{ comment.content }}</p> 
                        </li>
                        {% endfor %}
                    {% endif %}
                </ul>
                <p class="card__created-at">{{ post.created_at|date:"Y년 m월 d일" }}</p>
            </div>
        </div>
    </div>
</div>

LIONGRAM/templates/posts/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %} 인덱스 {% endblock %}

{% block content %}
<h1> 삭제 </h1>
<form action="" method="POST">
    {% csrf_token %}
    <p>한번 삭제된 데이터는 복구가 불가능합니다.</p><br/>
    <p>그래도 삭제하시겠습니까? ID : {{ post.id }}</p><br/><br/>
    <a href="{% url 'index' %}">돌아가기</a>
    <input type="submit" value="삭제하기">
</form>
<hr>
{% include 'mixin/posts/post_card.html' with detail=True %}
{% endblock %}

LIONGRAM/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} 글 상세 {% endblock %}

{% block content %}
<h1> 상세 </h1>
{% include 'mixin/posts/post_card.html' with detail=True %}
    {{ form.as_p }}
{% endblock %}

LIONGRAM/templates/posts/post_form.html
{% extends 'base.html' %}
{% block title %} 글 입력 {% endblock %}

{% block content %}
<h1> POST 입력 화면 </h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <label for="id_image">image</label>
        {% if post.image %}
            <p>current: <a href="{{post.image.url}}">{{ post.image.name }}</a></p>
            <p>change: <input type="file" name="image" accept="image/*" id="id_image"></p>
        {% else %}
            <input type="file" name="image" accept="image/*" id="id_image">
        {% endif %}
    </div>
    <div>
        <label for="id_content">content</label>
        <textarea name="content" id="id_content" cols="30" rows="10">{% if post %}{{ post.content }}{% endif %}</textarea>
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

LIONGRAM/templates/posts/post_form2.html
{% extends 'base.html' %}
{% block title %} 글 입력 {% endblock %}

{% block content %}
<h1> POST 입력 화면 - Form 사용</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        <!-- {# {{ form.as_p }} #} -->
        {{ form.as_p }}
        <!-- {% for field in form %}
            <label for="{{ field.id_for_label }}">{{ field.html_name }}</label>
        {% endfor %} -->
    </div>
    <div>
        <input type="submit">
    </div>
</form>
{% endblock %}

LIONGRAM/templates/posts/post_list.html
{% extends 'base.html' %}
{% block title %} 인덱스 {% endblock %}

{% block content %}
<h1> 목록 </h1>
{% for post in post_list %}
    <div>
        {{ post.id }}</br/>
        {{ post.image }}</br/>
        {{ post.content }}</br/>
        {{ post.created_at }}</br/>
        {{ post.writer }}</br/>
    </div>

{% endfor %}
{% endblock %}